// =============================================================================
// analogCatalog.ts — Historical Analog Library  (WO-SA20)
// 10 entries covering major US market regime episodes
// =============================================================================
import type { AnalogEntry } from '@/types/analog'

export const ANALOG_CATALOG: AnalogEntry[] = [
  {
    label:       '2022 Fed Bear',
    period:      'Jan 2022 – Oct 2022',
    regime:      'STRUCTURAL',
    runtime_mode:'LOCKDOWN',
    shock_type:  'POLICY',
    macro_env:   'TIGHTENING',
    policy_gates:'BLOCKED',
    forward_return_5d:  -1.8,
    forward_return_20d: -6.2,
    max_drawdown:       -15.0,
    notes: 'Aggressive Fed tightening cycle, QQQ -35% peak-to-trough',
  },
  {
    label:       '2020 COVID Crash',
    period:      'Feb 2020 – Mar 2020',
    regime:      'EVENT',
    runtime_mode:'LOCKDOWN',
    shock_type:  'LIQUIDITY',
    macro_env:   'EASING',
    policy_gates:'BLOCKED',
    forward_return_5d:  -7.2,
    forward_return_20d: -18.4,
    max_drawdown:       -34.0,
    notes: 'Sudden external shock, rapid Fed response',
  },
  {
    label:       '2018 Q4 Selloff',
    period:      'Oct 2018 – Dec 2018',
    regime:      'EVENT',
    runtime_mode:'DEFENSIVE',
    shock_type:  'POLICY',
    macro_env:   'TIGHTENING',
    policy_gates:'LIMITED',
    forward_return_5d:  -2.1,
    forward_return_20d: -8.7,
    max_drawdown:       -19.8,
    notes: 'Rate fears + trade war; sharp V-bottom recovery',
  },
  {
    label:       '2020 Recovery',
    period:      'Apr 2020 – Aug 2020',
    regime:      'NORMAL',
    runtime_mode:'NORMAL',
    shock_type:  'NONE',
    macro_env:   'EASING',
    policy_gates:'OPEN',
    forward_return_5d:  2.9,
    forward_return_20d: 10.1,
    max_drawdown:       -5.0,
    notes: 'Post-shock liquidity rally; stimulus-driven recovery',
  },
  {
    label:       '2015 China Shock',
    period:      'Aug 2015 – Sep 2015',
    regime:      'EVENT',
    runtime_mode:'DEFENSIVE',
    shock_type:  'MACRO',
    macro_env:   'NEUTRAL',
    policy_gates:'LIMITED',
    forward_return_5d:  -1.5,
    forward_return_20d: -4.3,
    max_drawdown:       -12.4,
    notes: 'CNY devaluation + global growth fears',
  },
  {
    label:       '2023 Banking Crisis',
    period:      'Mar 2023 – May 2023',
    regime:      'EVENT',
    runtime_mode:'DEFENSIVE',
    shock_type:  'CREDIT',
    macro_env:   'TIGHTENING',
    policy_gates:'LIMITED',
    forward_return_5d:  -0.8,
    forward_return_20d: 3.2,
    max_drawdown:       -7.5,
    notes: 'SVB/Signature collapse; contained by FDIC backstop',
  },
  {
    label:       '2019 Bull Extension',
    period:      'Jan 2019 – Jul 2019',
    regime:      'NORMAL',
    runtime_mode:'NORMAL',
    shock_type:  'NONE',
    macro_env:   'EASING',
    policy_gates:'OPEN',
    forward_return_5d:  1.4,
    forward_return_20d: 5.8,
    max_drawdown:       -3.2,
    notes: 'Fed pivot from tightening; sustained uptrend',
  },
  {
    label:       '2021 Rotation',
    period:      'Sep 2021 – Nov 2021',
    regime:      'HYBRID',
    runtime_mode:'LIMITED',
    shock_type:  'POLICY',
    macro_env:   'TIGHTENING',
    policy_gates:'LIMITED',
    forward_return_5d:  0.3,
    forward_return_20d: -2.1,
    max_drawdown:       -8.0,
    notes: 'Taper fears; growth → value rotation',
  },
  {
    label:       '2016 Post-Brexit',
    period:      'Jul 2016 – Dec 2016',
    regime:      'HYBRID',
    runtime_mode:'LIMITED',
    shock_type:  'MACRO',
    macro_env:   'NEUTRAL',
    policy_gates:'LIMITED',
    forward_return_5d:  1.1,
    forward_return_20d: 4.5,
    max_drawdown:       -4.5,
    notes: 'Initial shock absorbed; reflation trade lifted markets',
  },
  {
    label:       '2011 Debt Ceiling',
    period:      'Jul 2011 – Oct 2011',
    regime:      'STRUCTURAL',
    runtime_mode:'DEFENSIVE',
    shock_type:  'POLICY',
    macro_env:   'NEUTRAL',
    policy_gates:'BLOCKED',
    forward_return_5d:  -2.5,
    forward_return_20d: -5.5,
    max_drawdown:       -19.0,
    notes: 'US downgrade + European debt crisis overlap',
  },
]
