"""
Build sector_rotation.json — single source of truth for all sector rotation UI.

Reads (already generated by pipeline):
  output/sector_performance.json  →  sector_perf (1D/1W/1M/3M/6M/1Y)
  output/rotation_picks.json      →  phase / leading_sectors / top10

Writes:
  output/sector_rotation.json

Also ensures core ETF symbols are present in universe_symbols
so update_ohlcv.py will pick them up on the next DB update run.
"""
from __future__ import annotations

import json
import os
import sqlite3
import traceback
from datetime import datetime
from typing import Any, Dict, List, Optional


# ── 핵심 섹터 ETF + 벤치마크 ──────────────────────────────────────
SECTOR_ETFS: List[str] = [
    'XLK', 'XLV', 'XLF', 'XLE', 'XLY',
    'XLP', 'XLI', 'XLB', 'XLRE', 'XLU', 'XLC',
]
BENCHMARK_ETFS: List[str] = ['SPY', 'QQQ', 'IWM', 'DIA']
ALL_CORE_ETFS: List[str] = SECTOR_ETFS + BENCHMARK_ETFS

ETF_NAMES: Dict[str, str] = {
    'XLK':  'Technology',
    'XLV':  'Healthcare',
    'XLF':  'Financials',
    'XLE':  'Energy',
    'XLY':  'Consumer Discret.',
    'XLP':  'Consumer Staples',
    'XLI':  'Industrials',
    'XLB':  'Materials',
    'XLRE': 'Real Estate',
    'XLU':  'Utilities',
    'XLC':  'Communication',
    'SPY':  'S&P 500',
    'QQQ':  'Nasdaq 100',
    'IWM':  'Russell 2000',
    'DIA':  'Dow Jones',
}

PHASE_LABELS = {
    'early_recovery': 'Early Recovery',
    'expansion':      'Expansion',
    'peak':           'Peak',
    'slowdown':       'Slowdown',
}

PHASE_COLOR = {
    'early_recovery': '#22c55e',
    'expansion':      '#00D9FF',
    'peak':           '#f59e0b',
    'slowdown':       '#ef4444',
}


def repo_root() -> str:
    return os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))


def db_path() -> str:
    return os.path.join(repo_root(), 'data', 'marketflow.db')


def output_dir() -> str:
    # backend/output/ is the canonical output directory (same as app.py OUTPUT_DIR)
    return os.path.join(os.path.dirname(__file__), '..', 'output')


def now_iso() -> str:
    return datetime.now().isoformat(timespec='seconds')


def load_json(filename: str) -> Optional[Dict[str, Any]]:
    path = os.path.join(output_dir(), filename)
    if not os.path.exists(path):
        return None
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def write_json(filename: str, data: Any) -> str:
    path = os.path.join(output_dir(), filename)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    return path


# ── DB: 핵심 ETF가 universe_symbols에 없으면 추가 ─────────────────
def ensure_etfs_in_universe(conn: sqlite3.Connection) -> Dict[str, int]:
    """Insert missing ETF symbols so update_ohlcv picks them up."""
    added = 0
    already = 0
    now = now_iso()
    for symbol in ALL_CORE_ETFS:
        exists = conn.execute(
            'SELECT 1 FROM universe_symbols WHERE symbol=?', (symbol,)
        ).fetchone()
        if not exists:
            conn.execute(
                """
                INSERT INTO universe_symbols
                  (symbol, name, sector, industry, exchange, market_cap,
                   is_active, is_top100, last_updated)
                VALUES (?,?,?,?,?,NULL,1,0,?)
                """,
                (symbol, ETF_NAMES.get(symbol, symbol), 'ETF', 'Exchange Traded Fund',
                 'NYSE/NASDAQ', now),
            )
            added += 1
        else:
            already += 1
    conn.commit()
    return {'added': added, 'already': already}


# ── DB: OHLCV 커버리지 조회 ────────────────────────────────────────
def get_coverage(conn: sqlite3.Connection) -> Dict[str, Any]:
    total_universe = conn.execute(
        'SELECT COUNT(*) FROM universe_symbols WHERE is_active=1'
    ).fetchone()[0]
    ohlcv_symbols = conn.execute(
        'SELECT COUNT(DISTINCT symbol) FROM ohlcv_daily'
    ).fetchone()[0]
    latest_date_row = conn.execute(
        'SELECT MAX(date) FROM ohlcv_daily'
    ).fetchone()
    latest_date = latest_date_row[0] if latest_date_row else None

    etf_in_db = conn.execute(
        f"SELECT symbol FROM ohlcv_daily WHERE symbol IN "
        f"({','.join('?' for _ in SECTOR_ETFS)}) "
        f"GROUP BY symbol",
        SECTOR_ETFS,
    ).fetchall()
    etf_covered = [r[0] for r in etf_in_db]
    etf_missing  = [s for s in SECTOR_ETFS if s not in etf_covered]

    return {
        'ohlcv_symbols':   ohlcv_symbols,
        'total_universe':  total_universe,
        'coverage_pct':    round(ohlcv_symbols / total_universe * 100, 1) if total_universe > 0 else 0.0,
        'latest_date':     latest_date,
        'etf_covered':     etf_covered,
        'etf_missing':     etf_missing,
        'etf_missing_cnt': len(etf_missing),
        'low_coverage':    ohlcv_symbols < 100,
    }


# ── sector_performance.json → sector_perf with rankings ──────────
def build_sector_perf(perf_json: Optional[Dict[str, Any]]) -> List[Dict[str, Any]]:
    if not perf_json:
        return []
    sectors = perf_json.get('sectors', [])
    if not sectors:
        return []

    # 3M 기준 rank 부여
    ranked_3m = sorted(sectors, key=lambda x: x.get('change_3m', 0), reverse=True)
    rank_map = {s['symbol']: i + 1 for i, s in enumerate(ranked_3m)}

    result = []
    for s in sectors:
        sym = s.get('symbol', '')
        result.append({
            'symbol':     sym,
            'name':       s.get('name', sym),
            'price':      s.get('price'),
            'change_1d':  s.get('change_1d'),
            'change_1w':  s.get('change_1w'),
            'change_1m':  s.get('change_1m'),
            'change_3m':  s.get('change_3m'),
            'change_6m':  s.get('change_6m'),
            'change_1y':  s.get('change_1y'),
            'rank_3m':    rank_map.get(sym, 99),
        })
    return result


# ── leading / lagging 섹터 판단 ───────────────────────────────────
def derive_leaders_laggers(
    sector_perf: List[Dict[str, Any]],
    rotation_json: Optional[Dict[str, Any]],
) -> tuple[List[str], List[str]]:
    """Return (leading_sectors top3, lagging_sectors bottom3) by 3M."""
    # rotation_picks.json의 leading_sectors 있으면 우선 사용
    if rotation_json and rotation_json.get('leading_sectors'):
        leading = rotation_json['leading_sectors'][:3]
    elif sector_perf:
        by_3m = sorted(sector_perf, key=lambda x: x.get('change_3m') or 0, reverse=True)
        leading = [s['symbol'] for s in by_3m[:3]]
    else:
        leading = []

    if sector_perf:
        by_3m_asc = sorted(sector_perf, key=lambda x: x.get('change_3m') or 0)
        lagging = [s['symbol'] for s in by_3m_asc[:3] if s['symbol'] not in leading]
    else:
        lagging = []

    return leading, lagging


def main() -> int:
    # ── DB 연결 ──
    db = db_path()
    if not os.path.exists(db):
        print(f'[ERROR] DB not found: {db}')
        return 1

    conn = sqlite3.connect(db)
    try:
        etf_status = ensure_etfs_in_universe(conn)
        coverage   = get_coverage(conn)
    finally:
        conn.close()

    # ── 기존 JSON 로드 ──
    perf_json     = load_json('sector_performance.json')
    rotation_json = load_json('rotation_picks.json')

    # ── 섹터 퍼포먼스 가공 ──
    sector_perf = build_sector_perf(perf_json)

    # ── leading / lagging ──
    leading, lagging = derive_leaders_laggers(sector_perf, rotation_json)

    # ── rotation_picks_top10 ──
    rotation_picks_top = []
    if rotation_json:
        rotation_picks_top = rotation_json.get('top10', [])

    # ── 현재 phase ──
    phase       = (rotation_json or {}).get('phase', 'unknown')
    phase_label = PHASE_LABELS.get(phase, phase)
    phase_color = PHASE_COLOR.get(phase, '#6b7280')

    # ── 최종 출력 ──
    updated_at     = now_iso()
    total_symbols  = coverage['ohlcv_symbols']
    coverage_ratio = coverage['coverage_pct']

    output: Dict[str, Any] = {
        'generated_at':        updated_at,
        'updated_at':          updated_at,
        'total_symbols':       total_symbols,
        'coverage_ratio':      coverage_ratio,
        'source_perf_ts':      (perf_json or {}).get('timestamp'),
        'source_rotation_ts':  (rotation_json or {}).get('timestamp'),
        'phase':               phase,
        'phase_label':         phase_label,
        'phase_color':         phase_color,
        'leading_sectors':     leading,
        'lagging_sectors':     lagging,
        'sector_perf':         sector_perf,
        'rotation_picks_top':  rotation_picks_top,
        'coverage':            coverage,
        'etf_registry_update': etf_status,
    }

    out_path = write_json('sector_rotation.json', output)

    # ── 로그 ──
    print('=' * 62)
    print('build_sector_rotation_cache.py')
    print(f'[OK] phase={phase}  leading={leading}  lagging={lagging}')
    print(f'[OK] sector_perf={len(sector_perf)}  picks_top={len(rotation_picks_top)}')
    print(f'[OK] coverage={coverage["ohlcv_symbols"]}/{coverage["total_universe"]} '
          f'({coverage["coverage_pct"]}%)')
    if coverage['etf_missing']:
        print(f'[WARN] ETF missing from ohlcv_daily: {coverage["etf_missing"]}')
        print(f'       → Run update_ohlcv.py to fetch ETF OHLCV data')
    if etf_status['added']:
        print(f'[INFO] Added {etf_status["added"]} ETFs to universe_symbols → '
              f'will be fetched on next update_ohlcv run')
    print(f'[OK] {out_path}')
    print('=' * 62)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
